Update IncTasks.py
stevenctran/Incident-Viewer pull request #1
Opened 2020-12-02 03:50 UTC by stevenctran

2020-12-02 04:12 UTC, alvinqle requested changes

2020-12-02 04:12 UTC, alvinqle commented on Incident-Viewer.py
> +import time
nit - Reorder the imports as such:

1) Built-in packages
2) 3rd party packages
3) Customer user modules

Then alphabetize the packages in that order

2020-12-02 04:12 UTC, alvinqle commented on Incident-Viewer.py
> +startTime = datetime.now()
nit - PEP8 recommends variable names use underscore instead of camel case, i.e. `start_time`

2020-12-05 03:23 UTC, alvinqle requested changes
Some small changes - overall pretty clean

2020-12-05 03:23 UTC, alvinqle commented on Incident-Viewer.py
> +    driver.implicitly_wait(2)
Is there a particular reason why 2 was chosen as the parameter here? Is it arbitrary?

2020-12-05 03:23 UTC, alvinqle commented on Incident-Viewer.py
> +    driver.implicitly_wait(1)
Same as comment for line 18

2020-12-05 03:23 UTC, alvinqle commented on Incident-Viewer.py
> +        unassigned_inc_count.click()
These 2 conditionals do the same thing, can remove the elif conditional

2020-12-05 03:23 UTC, alvinqle commented on Incident-Viewer.py
> +        unassigned_inc_count.click()
Oh wait, I just saw that incident is plural when it's greater than 1, in that case I'd replace the text with something like incident(s) to reduce code bloat

2020-12-05 03:23 UTC, alvinqle commented on Incident-Viewer.py
> +        unassigned_task_count.click()
Same as comment for lines 21-26

2020-12-05 03:23 UTC, alvinqle commented on Incident-Viewer.py
> +    for b in body.find_elements_by_xpath('//tr[@class="list_group"]'):
nit - `b` is pretty vague for a variable name

2020-12-05 03:23 UTC, alvinqle commented on Incident-Viewer.py
> +        print(incidents.text)
Couldn't you get rid of this for loop and print `incidents.text` when you iterate through `incident_list` below?

2020-12-05 03:23 UTC, alvinqle commented on Incident-Viewer.py
> +    i, tickets = [], []
nit - `i` is a pretty vague variable name

2020-12-05 03:23 UTC, alvinqle commented on Incident-Viewer.py
> +        tickets.append(i[:])
What happens if `i` is an empty list? Maybe add a conditional to only append `i` if it's not empty

2020-12-05 03:23 UTC, alvinqle commented on Incident-Viewer.py
> +        print(tasks.text)
Same as one of the comments above - you can get rid of this for loop and move `print(tasks.text)` within the one below to save 1 full iteration of this for loop

2020-12-05 03:23 UTC, alvinqle commented on Incident-Viewer.py
> +    i, tickets = [], []
nit - `i` is a vague variable name

2020-12-05 03:23 UTC, alvinqle commented on Incident-Viewer.py
> +        tickets.append(i[:])
Same as comment for line 60

2020-12-05 03:23 UTC, alvinqle commented on Incident-Viewer.py
> +    url =
Uninitialized variable - I think this would cause the interpreter to fail

2020-12-05 03:23 UTC, alvinqle commented on Incident-Viewer.py
> +        .sort_values('Location')
nit - I'd move this method call back up to the previous line, it's a bit confusing for readability

2020-12-05 03:23 UTC, alvinqle commented on Incident-Viewer.py
> +    os.startfile(filepath)
Having this method is a little redundant for how much it does - you can move these two lines under `if __name__ == '__main__'`

2020-12-05 08:41 UTC, stevenctran commented on Incident-Viewer.py
> +    driver.implicitly_wait(2)
While I was testing, it would error out because the next element wasn't found so I put a wait there.

2020-12-05 08:41 UTC, stevenctran commented on Incident-Viewer.py
> +    driver.implicitly_wait(1)
Same as above

2020-12-05 08:41 UTC, stevenctran commented on Incident-Viewer.py
> +        unassigned_inc_count.click()
Ah smart idea. Was wondering how programmers get around this. Will change that

2020-12-05 08:41 UTC, stevenctran commented on Incident-Viewer.py
> +        unassigned_task_count.click()
Will do

2020-12-05 08:42 UTC, stevenctran commented on Incident-Viewer.py
> +    for b in body.find_elements_by_xpath('//tr[@class="list_group"]'):
Gotcha. Will change variables name

2020-12-05 08:42 UTC, stevenctran commented on Incident-Viewer.py
> +    i, tickets = [], []
Same as above

2020-12-05 08:43 UTC, stevenctran commented on Incident-Viewer.py
> +        print(incidents.text)
Not that I know of. body.find_elements_by_xpath('//tr[@record_class="incident"]') outputs a list so I have to iterate through each incident to get the text.

2020-12-05 08:43 UTC, stevenctran commented on Incident-Viewer.py
> +    i, tickets = [], []
Will change

2020-12-05 08:43 UTC, stevenctran commented on Incident-Viewer.py
> +        tickets.append(i[:])
When it's empty, it outputs nothing so it is working as intended.. Should I still change it?

2020-12-05 09:29 UTC, stevenctran commented on Incident-Viewer.py
> +    url =
Oh I took out the URL for this since it's in a public github (i think?)

2020-12-05 09:30 UTC, stevenctran commented on Incident-Viewer.py
> +    os.startfile(filepath)
Still learning how main works so good to know. I'll move it there

2020-12-06 05:26 UTC, alvinqle commented on Incident-Viewer.py
> +    driver.implicitly_wait(2)
Yeah I get that, just wondering if there's a particular reason you used 2

2020-12-06 05:27 UTC, alvinqle commented on Incident-Viewer.py
> +    url =
Got it, in that case you can prob treat this variable as something similar to credentials and load it via json or as an environment variable so that you don't have to remove it every time to push to Git

2020-12-06 05:28 UTC, alvinqle commented on Incident-Viewer.py
> +        print(incidents.text)
Right, but on line 48 you set `incident_list` equal to the same thing you're iterating through here, and then iterate through `incident_list` on line 56, so you could just move the print statement into that iteration on line 56 and remove this for loop

2020-12-07 17:04 UTC, stevenctran commented on Incident-Viewer.py
> +    driver.implicitly_wait(2)
If I put 1, it would error out, but 2 allowed it to go through.

2020-12-07 17:06 UTC, stevenctran commented on Incident-Viewer.py
> +    driver.implicitly_wait(1)
1 Actually works here because it loads the page going downwards. So by the time the first element loaded, this one loaded alongside it

2020-12-07 17:29 UTC, stevenctran commented on Incident-Viewer.py
> +        print(incidents.text)
Oh wait I see what you mean. Tested it and consolidated it into: 
`    for inc in body.find_elements_by_xpath('//tr[@class="list_group"]'):
        inc.find_element_by_tag_name('button').click()
        incident_list.append(body.find_element_by_xpath('//tr[@record_class="incident"]'))
        print(body.find_element_by_xpath('//tr[@record_class="incident"]').text)`

2020-12-07 17:33 UTC, stevenctran commented on Incident-Viewer.py
> +        print(incidents.text)
Just kidding. I can't do that. It prints the first INC twice multiplied by however many cases there are. Had to change it back.

2020-12-07 18:08 UTC, stevenctran commented on Incident-Viewer.py
> +        .sort_values('Location')
Moved back to line 114.

2020-12-07 18:09 UTC, stevenctran commented on Incident-Viewer.py
> +    os.startfile(filepath)
Moved to if __name__ == '__main__'

2020-12-07 19:01 UTC, stevenctran commented on Incident-Viewer.py
> +    url =
Okay just updated it to load a json file with the URL.

2020-12-07 19:01 UTC, stevenctran commented on Incident-Viewer.py
> +    i, tickets = [], []
Changed i to ticket

2020-12-07 19:02 UTC, stevenctran commented on Incident-Viewer.py
> +    i, tickets = [], []
Changed i to ticket

2020-12-07 19:02 UTC, stevenctran commented on Incident-Viewer.py
> +        print(tasks.text)
If you're ever free, let's do a meeting so we can review this. I'm not sure if there is a way to change it.

2020-12-07 19:03 UTC, stevenctran commented on Incident-Viewer.py
> +    for b in body.find_elements_by_xpath('//tr[@class="list_group"]'):
Changed b to inc

2020-12-07 19:03 UTC, stevenctran commented on Incident-Viewer.py
> +        unassigned_task_count.click()
Updated and removed the elif. Changed to unassigned task(s)

2020-12-07 19:03 UTC, stevenctran commented on Incident-Viewer.py
> +        unassigned_inc_count.click()
Removed elif. Changed to unassigned incident(s)

2020-12-07 19:04 UTC, stevenctran commented on Incident-Viewer.py
> +    driver.implicitly_wait(1)
Had to change it to time.sleep() as that was more consistent when running it.

2020-12-07 19:08 UTC, merged